# Generated by Django 3.1.1 on 2020-10-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_userprofile_extra_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vision',
            field=models.IntegerField(default=0),
        ),
    ]
