# Generated by Django 3.1.1 on 2021-01-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_userprofile_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consecutive_correct_ans',
            field=models.IntegerField(default=0),
        ),
    ]
