# Generated by Django 3.1.1 on 2021-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_userprofile_consecutive_correct_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='no_switch',
            field=models.IntegerField(default=2),
        ),
    ]
