# Generated by Django 3.1.1 on 2021-02-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_userprofile_no_switch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='no_switch',
        ),
    ]
