# Generated by Django 3.1.1 on 2021-02-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_remove_userprofile_no_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
